name: CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install, Build, Test E2E
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn start
      - name: Build JS/TS SDK
        if: github.event.pull_request.merged == true
        run: yarn build:sdk
      - name: Publish JS/TS SDK
        if: github.event.pull_request.merged == true
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
