name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn start
      - name: Build JS/TS SDK
        run: yarn build:sdk
      - name: Publish JS/TS SDK
        run: npm publish
        working-directory: ./dist/sdk
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
